### ISSUE TITLE
Why is a nuxt module needed to make helmet work in Nuxt?

### ISSUE THREAD

**Issue by komplexb** [victor-perez/nuxt-helmet#100]
Hi Victor, 
Thanks for making this.

Can you explain or point me to some documentation that explains why helmet needs to be implemented as a nuxt module instead of being required as express middleware. As in why doesn't placing it in [index.js](https://github.com/nuxt-community/express-template/blob/master/api/index.js) work?

Please let me know thanks.

**Comment by victor-perez** [comment]
If you use Express to run Nuxt, you can just use [Helmet](https://www.npmjs.com/package/helmet) in your `index.js`. But by default Nuxt doesn't uses Express, it's using [Connect](https://www.npmjs.com/package/connect) and in that case the easiest way to implement Helmet is [nuxt-helmet](https://www.npmjs.com/package/nuxt-helmet). I hope that this answer your question

**Comment by komplexb** [comment]
Sorry for the late response. 

So if I understand you correctly, the issue is that Helmet is Express middleware, and doesn't natively work with Connext?

**Comment by victor-perez** [comment]
@komplexb that is not what I meant. You pointed to the index.js of the (express-template)[https://github.com/nuxt-community/express-template] when you use this template you can use Helmet directly. But  when you do a "normal" Nuxt installation (https://nuxtjs.org/docs/2.x/get-started/installation) then you need to use nuxt-helmet
