### ISSUE TITLE
Breaking helmet upgrade

### ISSUE THREAD

**Issue by rchl** [victor-perez/nuxt-helmet#129]
I've been using v2.0.1 which has used Helmet 4. Now that I've upgraded to v2.1.0 things broke because it's using Helmet 5 and there are breaking changes in Helmet 5.

Why was minor version of the module released with a breaking Helmet upgrade?

**Comment by victor-perez** [comment]
Sorry for the inconvenience, my own upgrade to Helmet 5 went without any problems. So I assume wrongly that it was a minor version. I can't anymore remove v2.1.0 I can only make it deprecated.

**Comment by rchl** [comment]
Thanks.

It's good that you can't remove v2.1.0 because that would break projects in even worse way (npm install would fail).

What you should do though is you should also release 2.1.1 (or 2.2.0) that reverts helmet to version 4.
