### ISSUE TITLE
Nuxt Helmet config options after the nuxt-helmet module

### ISSUE THREAD

**Issue by wolfiton** [victor-perez/nuxt-helmet#18]
Hi @victor-perez,

I have a problem understanding where in my nuxt config the following configuration go:

```js
helmet: {
    
    dnsPrefetchControl: true,
    expectCt: true,
    featurePolicy: true,
    frameguard: true,
    hidePoweredBy: true,
    hsts: true,
    ieNoOpen: true,
    noCache: true,
    noSniff: true,
    permittedCrossDomainPolicies: true,
    referrerPolicy: true,
    xssFilter: true,
    
 }
```

Because if I put it after my modules my nuxt app will not compile anymore here is what I was trying to do:
```js
modules: [
    'nuxt-helmet',

    '@nuxtjs/pwa',
    // Doc: https://github.com/nuxt-community/dotenv-module
    '@nuxtjs/dotenv'
  ],

helmet: {
    
    dnsPrefetchControl: true,
    expectCt: true,
    featurePolicy: true,
    frameguard: true,
    hidePoweredBy: true,
    hsts: true,
    ieNoOpen: true,
    noCache: true,
    noSniff: true,
    permittedCrossDomainPolicies: true,
    referrerPolicy: true,
    xssFilter: true,
    
 }
```

Can you please tell me what I am doing wrong?

On the backend I am using something else other than javascript or node server derivates, that is why I am asking how to configure your module to work with Nuxt with a setup like:

- Python, ruby backend graphql and nuxt

Thanks

**Comment by victor-perez** [comment]
@wolfiton can you share you nuxt config file and/or the error that you get ?

**Comment by wolfiton** [comment]
Hi @victor-perez,

Thank you for the quick reply, I created this git repo https://github.com/wolfiton/debug-nuxt-helmet with a minimal frontend so you can have the same setup as me.

Also my errors is related to this:

```js 
✖ Nuxt Fatal Error                                                                                                │
   │                                                                                                                     │
   │   Error: featurePolicy must have a single key, "features", which is an object of features. See the documentation.
```

**Comment by victor-perez** [comment]
Hi @wolfiton 
You can find the full Helmet documentation at https://helmetjs.github.io/ and the documentation about the `featurePolicy` is at https://helmetjs.github.io/docs/feature-policy/

The default config of `nuxt-helmet` is the default config of Helmet (https://helmetjs.github.io/docs/) + `permittedCrossDomainPolicies` set to `true`

Sorry that the documentation is not clear but you don't need to add the `helmet` config object in your config. If you want to use the default config. You only need the `helmet` config object if you want to change the default config.  ( and the default config is most of the time the only thing you need )

> Also I have one more question does the helmet headers also protect my graphql api?
This only added the headers for Nuxt pages, so it will not added this to graphql api 

> Do I also need to set headers on the backend as well?
Depending on your implementation it wise to set some of these headers also there

**Comment by wolfiton** [comment]
Thanks @victor-perez  for all the help really apreciated
