### ISSUE TITLE
Can this be used with static stites?

### ISSUE THREAD

**Issue by SimonFricker** [victor-perez/nuxt-helmet#21]
I'm sure this is a silly question but can this be used with static site generation?

**Comment by wolfiton** [comment]
If you intend to use it to protect your static site than there is no need. But if you have other parts in your app that change data through forms or other ways. Then this is a good fit to bring some security headers for your services.

Please provide more details on what type of project you have.

For example, for a blog with comments, this can be very useful.

**Comment by victor-perez** [comment]
closed because

**Comment by solidevolution** [comment]
@victor-perez i'm not sure if this is possible for all helmet security features but wouldn't it be perfect, if this module sets `<meta>`-Tags on SSG instead of HTTP Headers in SSR?
