### ISSUE TITLE
Need help with loading JS in a component

### ISSUE THREAD

**Issue by d4rkr3pt0r** [victor-perez/nuxt-helmet#6]
Hi
I'm looking for a way to put a `script` tag in my component. ( Not in head BUT somewhere inside HTML codes). The script tag is like: `<script src="http://example.com/page/"></script>`.
Actually it tries to inject an HTML button to the page and it works fine with a simple HTML page.
But in Nuxt app It shows up for a second and disappears.
The console is logging the following warning regarding this issue: 
`The script from “http://example.com/page/” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.[Learn More]`

I couldn't fix it using this library and the problem still exist.
Any help?

**Comment by victor-perez** [comment]
Unrelated to the plugin
