### ISSUE TITLE
Not working after 'nuxt build'

### ISSUE THREAD

**Issue by seandan7** [victor-perez/nuxt-helmet#63]
I believe this package works locally, but the headers are lost after running nuxt build. 

This may be related to the helmet package v4 upgrade?

**Comment by victor-perez** [comment]
@seandan7 I expected that you build in SPA mode. Are you running on production `nuxt-start`? HTTP headers can only be set by the server, meaning if you don't use Nuxt server (a.k.a. `nuxt-start`) as you server _nuxt-helmet_ wil not work.

**Comment by seandan7** [comment]
Okay, gotcha. Thank you!
