### ISSUE TITLE
Import error when running nuxt

### ISSUE THREAD

**Issue by Ankarrr** [victor-perez/nuxt-helmet#70]
I got this error after I install the package and configure it in `nuxt.config.js`. Please help with this!

![截圖 2020-10-23 下午6 53 54](https://user-images.githubusercontent.com/8311552/96995665-1ef02e00-1561-11eb-8063-12a5645e3c93.png)

**Comment by victor-perez** [comment]
Looks like babel is not correctly configurated, can you share your `nuxt.config.js` ?
