### ISSUE TITLE
not hide X-Powered-By: Express 

### ISSUE THREAD

**Issue by Mitch-i** [victor-perez/nuxt-helmet#86]
X-Content-Type-Options: nosniff
X-DNS-Prefetch-Control: off
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Powered-By: Express
X-XSS-Protection: 0

**Comment by victor-perez** [comment]
@Mitch-i  what is you setup? by default Nuxt doesn't uses Express. When you use a custom setup Nuxt setup with Express I would use [helmet](https://www.npmjs.com/package/helmet) directly in Express and not via `nuxt-helmet`
